apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: phpapp
    app.kubernetes.io/component: phpapp
    app.kubernetes.io/instance: phpapp
  name: phpapp
  namespace: phpapp
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: phpapp
  sessionAffinity: None
  type: ClusterIP
